# Generated by Django 5.2.7 on 2025-11-08 17:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('album_type', models.CharField(max_length=50)),
                ('cover_image', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'catalog_album',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('korean_name', models.CharField(max_length=100)),
                ('debut_date', models.DateField()),
                ('agency', models.CharField(max_length=100)),
                ('group_type', models.CharField(max_length=50)),
                ('logo_image', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'catalog_group',
            },
        ),
        migrations.CreateModel(
            name='AlbumVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_name', models.CharField(max_length=100)),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('number_of_photocards', models.IntegerField(default=0)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='catalog.album')),
            ],
            options={
                'db_table': 'catalog_albumversion',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='catalog.group'),
        ),
        migrations.CreateModel(
            name='Lightstick',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=50)),
                ('image', models.URLField(blank=True, null=True)),
                ('release_date', models.DateField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lightsticks', to='catalog.group')),
            ],
            options={
                'db_table': 'catalog_lightstick',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_name', models.CharField(max_length=100)),
                ('real_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('position', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('profile_image', models.URLField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='catalog.group')),
            ],
            options={
                'db_table': 'catalog_member',
            },
        ),
        migrations.CreateModel(
            name='Photocard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('image', models.URLField(blank=True, null=True)),
                ('release_date', models.DateField()),
                ('photocard_type', models.CharField(max_length=50)),
                ('album_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photocards', to='catalog.albumversion')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photocards', to='catalog.group')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photocards', to='catalog.member')),
            ],
            options={
                'db_table': 'catalog_photocard',
            },
        ),
    ]
