# Generated by Django 5.2.7 on 2025-10-19 18:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCollectible',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collectible_type', models.CharField(choices=[('photocard', 'Photocard'), ('lightstick', 'Lightstick')], max_length=20)),
                ('source', models.CharField(max_length=100)),
                ('acquisition_date', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condition', models.CharField(max_length=50)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('photo', models.URLField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('lightstick', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_collectibles', to='catalog.lightstick')),
                ('photocard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_collectibles', to='catalog.photocard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectibles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_collectibles',
            },
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collectible_type', models.CharField(choices=[('photocard', 'Photocard'), ('lightstick', 'Lightstick')], max_length=20)),
                ('priority', models.DecimalField(decimal_places=1, max_digits=3)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('lightstick', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='catalog.lightstick')),
                ('photocard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='catalog.photocard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wishlist_items',
            },
        ),
        migrations.CreateModel(
            name='UserFavoriteGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorited_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_favorite_groups',
                'unique_together': {('user', 'group')},
            },
        ),
    ]
